name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.19.0
      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test

      - name: Build Web
        run: flutter build web

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: project/build/web/
